<html>
<head>
    <title>Отзыв</title>
    <meta charset="utf8">
</head>
<body>
<p>Отзыв</p>
<table>
    <tr>
        <th>Имя</th><th>{{$name}}</th>
    </tr>
    <tr>
        <td>Почта</td><td>{{$email}}</td>
    </tr>
    <tr>
        <td>Сообщение</td><td>{{$text}}</td>
    </tr>
</table>
</body>
</html>
